# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Information.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from connectDB import *
import main_layout
idDriver = 1

class Ui_frmInf(object):
    def setupUi(self, frmInf):
        frmInf.setObjectName("frmInf")
        frmInf.resize(480, 300)
        self.label = QtWidgets.QLabel(frmInf)
        self.label.setGeometry(QtCore.QRect(180, 10, 141, 31))
        self.label.setObjectName("label")
        self.btnSaveInf = QtWidgets.QPushButton(frmInf)
        self.btnSaveInf.setGeometry(QtCore.QRect(210, 260, 93, 28))
        self.btnSaveInf.setObjectName("btnSaveInf")
        self.license = QtWidgets.QLineEdit(frmInf)
        self.license.setGeometry(QtCore.QRect(140, 220, 141, 21))
        self.license.setObjectName("license")
        self.label_2 = QtWidgets.QLabel(frmInf)
        self.label_2.setGeometry(QtCore.QRect(70, 100, 55, 16))
        self.label_2.setObjectName("label_2")
        self.id_driver = QtWidgets.QLineEdit(frmInf)
        self.id_driver.setGeometry(QtCore.QRect(140, 61, 51, 21))
        self.id_driver.setReadOnly(True)
        self.id_driver.setObjectName("id_driver")
        self.age = QtWidgets.QLineEdit(frmInf)
        self.age.setGeometry(QtCore.QRect(140, 180, 71, 21))
        self.age.setObjectName("age")
        self.label_3 = QtWidgets.QLabel(frmInf)
        self.label_3.setGeometry(QtCore.QRect(70, 180, 55, 16))
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(frmInf)
        self.password.setGeometry(QtCore.QRect(310, 60, 141, 21))
        self.password.setObjectName("password")
        self.label_8 = QtWidgets.QLabel(frmInf)
        self.label_8.setGeometry(QtCore.QRect(70, 140, 55, 16))
        self.label_8.setObjectName("label_8")
        self.cbGender = QtWidgets.QComboBox(frmInf)
        self.cbGender.setGeometry(QtCore.QRect(140, 140, 73, 22))
        self.cbGender.setObjectName("cbGender")
        self.cbGender.addItem("")
        self.cbGender.addItem("")
        self.label_6 = QtWidgets.QLabel(frmInf)
        self.label_6.setGeometry(QtCore.QRect(240, 60, 55, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(frmInf)
        self.label_7.setGeometry(QtCore.QRect(70, 60, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(frmInf)
        self.label_4.setGeometry(QtCore.QRect(70, 220, 55, 16))
        self.label_4.setObjectName("label_4")
        self.name = QtWidgets.QLineEdit(frmInf)
        self.name.setGeometry(QtCore.QRect(140, 100, 151, 21))
        self.name.setObjectName("name")

        self.loadDriver()
        self.btnSaveInf.clicked.connect(lambda:self.saveInf(frmInf))
        self.retranslateUi(frmInf)
        QtCore.QMetaObject.connectSlotsByName(frmInf)

    def loadDriver(self):
        driver = getDriverById(idDriver)
        self.id_driver.setText(str(driver[0]))
        self.name.setText(driver[1])
        print(driver[2])
        if(driver[2] == 1):
            self.cbGender.setCurrentIndex(0)
        else:
            self.cbGender.setCurrentIndex(1)
        self.age.setText(str(driver[3]))
        self.license.setText(driver[4])
        self.password.setText(driver[7])
    def saveInf(self, frmInf):
        id = self.id_driver.text()
        password = self.password.text()
        name = self.name.text()
        gender = self.cbGender.currentIndex()
        age = self.age.text()
        license = self.license.text()
        
        print(age)
        if(name == "" or password==""):
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information) 
            msg.setWindowTitle("Save Information fail")
            msg.setText("Name or password cannot be empty!")
            msg.exec()
        else:
            driver = {
                "id": id, 
                "password": password, 
                "name": name, 
                "gender": gender, 
                "age": age, 
                "license": license
            }
            if(updateDriver(driver)):
                frmInf.close()
                self.window = QtWidgets.QMainWindow()
                self.ui = main_layout.Ui_main1()
                self.ui.setupUi(self.window)
                self.ui.label.setText("Hi " + name +", welcome to Driver Drowsiness Detection System")
                self.ui.label.setFont(QtGui.QFont('Georgia', 16))
                self.ui.label.setAlignment(QtCore.Qt.AlignCenter)
                main_layout.id = id
                self.window.show()
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information) 
                msg.setWindowTitle("Save Information")
                msg.setText("Save Information successfully!")
                msg.exec()
            else:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information) 
                msg.setWindowTitle("Save Information")
                msg.setText("Save Information fail!")
                msg.exec()

        
    def retranslateUi(self, frmInf):
        _translate = QtCore.QCoreApplication.translate
        frmInf.setWindowTitle(_translate("frmInf", "Information"))
        self.label.setText(_translate("frmInf", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Information</span></p></body></html>"))
        self.btnSaveInf.setText(_translate("frmInf", "Save"))
        self.label_2.setText(_translate("frmInf", "Name"))
        self.label_3.setText(_translate("frmInf", "Age"))
        self.label_8.setText(_translate("frmInf", "Gender"))
        self.cbGender.setItemText(0, _translate("frmInf", "Male"))
        self.cbGender.setItemText(1, _translate("frmInf", "Female"))
        self.label_6.setText(_translate("frmInf", "Password"))
        self.label_7.setText(_translate("frmInf", "Id"))
        self.label_4.setText(_translate("frmInf", "License"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmInf = QtWidgets.QDialog()
    ui = Ui_frmInf()
    ui.setupUi(frmInf)
    frmInf.show()
    sys.exit(app.exec_())
