# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import main_layout
from connectDB import *
from register import *
import copy

class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.setFixedSize(582, 361)
        login.setStyleSheet("#login{\n"
"background-repeat: no-repeat;\n"
"border-image: url(source/images/image2.jpg) 0 0 0 0 stretch stretch;\n"
"}")
        self.label = QtWidgets.QLabel(login)
        self.label.setGeometry(QtCore.QRect(320, 40, 81, 31))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(login)
        self.label_6.setGeometry(QtCore.QRect(320, 140, 55, 16))
        self.label_6.setObjectName("label_6")
        self.password = QtWidgets.QLineEdit(login)
        self.password.setGeometry(QtCore.QRect(320, 160, 141, 21))
        self.password.setObjectName("password")
        self.label_7 = QtWidgets.QLabel(login)
        self.label_7.setGeometry(QtCore.QRect(320, 80, 55, 16))
        self.label_7.setObjectName("label_7")
        self.id_driver = QtWidgets.QLineEdit(login)
        self.id_driver.setGeometry(QtCore.QRect(320, 100, 71, 21))
        self.id_driver.setText("")
        self.id_driver.setReadOnly(False)
        self.id_driver.setObjectName("id_driver")
        self.btnLogin = QtWidgets.QPushButton(login)
        self.btnLogin.setGeometry(QtCore.QRect(320, 210, 93, 28))
        self.btnLogin.setObjectName("btnLogin")
        self.btnRegister = QtWidgets.QPushButton(login)
        self.btnRegister.setGeometry(QtCore.QRect(450, 270, 90, 28))
        self.btnRegister.setAutoFillBackground(False)
        self.btnRegister.setStyleSheet("")
        self.btnRegister.setObjectName("btnRegister")
        self.label_2 = QtWidgets.QLabel(login)
        self.label_2.setGeometry(QtCore.QRect(320, 280, 131, 16))
        self.label_2.setObjectName("label_2")

        self.btnLogin.clicked.connect(lambda:self.login_UI(login))
        self.btnRegister.clicked.connect(lambda:self.register_UI(login))
        

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)


    def login_UI(self, login):
        _translate = QtCore.QCoreApplication.translate
        user = ()
        id = self.id_driver.text()
        password= self.password.text()

        if(id == "" or password==""):
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information) 
            msg.setWindowTitle("Invalid Login")
            msg.setText("ID or password can not empty")
            msg.exec()
        
        else:
            findUsers = list(getLogin(id, password).fetchall())
            
            if(len(findUsers) > 0):
                user = findUsers[0]
            if(user != ()):
                login.close()
                self.window = QtWidgets.QMainWindow()
                self.ui = main_layout.Ui_main1()
                self.ui.setupUi(self.window)
                self.ui.label.setText("Hi " + user[1] +", welcome to Driver Drowsiness Detection System")
                self.ui.label.setFont(QtGui.QFont('Georgia', 16))
                self.ui.label.setAlignment(QtCore.Qt.AlignCenter)
                main_layout.id = id
                self.window.show()
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information) 
                msg.setWindowTitle("Login successfully")
                msg.setText("Login successfully!")
                msg.exec()
            else:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information) 
                msg.setWindowTitle("Invalid Login")
                msg.setText("ID or password you entered is not valid, please try again!")
                msg.exec()
    def register_UI(self,login):
        login.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_frmRegister()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Login"))
        self.label.setText(_translate("login", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Login</span></p></body></html>"))
        self.label_6.setText(_translate("login", "Password"))
        self.label_7.setText(_translate("login", "Id"))
        self.btnLogin.setText(_translate("login", "Login"))
        self.btnRegister.setText(_translate("login", "Register"))
        self.label_2.setText(_translate("login", "Don\'t have an account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QDialog()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
