# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets        
from drowsinessDetection import *
import Information
import sound 
import login
from connectDB import *

id = 1

class Ui_main1(object):
    def setupUi(self, main1):
        main1.setObjectName("main1")
        main1.setFixedSize(829, 525)
        main1.setAutoFillBackground(False)
        main1.setStyleSheet("#main1{\n"
"background-repeat: no-repeat;\n"
"border-image: url(source/images/image2.jpg) 0 0 0 0 stretch stretch;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(main1)
        self.centralwidget.setObjectName("centralwidget")
        self.chooseSound = QtWidgets.QPushButton(self.centralwidget)
        self.chooseSound.setGeometry(QtCore.QRect(570, 180, 151, 51))
        self.chooseSound.setAutoFillBackground(False)
        self.chooseSound.setObjectName("chooseSound")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 831, 41))
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.editInf = QtWidgets.QPushButton(self.centralwidget)
        self.editInf.setGeometry(QtCore.QRect(570, 110, 151, 51))
        self.editInf.setAutoFillBackground(False)
        self.editInf.setObjectName("editInf")
        self.showCamera = QtWidgets.QPushButton(self.centralwidget)
        self.showCamera.setGeometry(QtCore.QRect(570, 250, 151, 51))
        self.showCamera.setAutoFillBackground(False)
        self.showCamera.setObjectName("showCamera")
        self.stopCamera = QtWidgets.QPushButton(self.centralwidget)
        self.stopCamera.setGeometry(QtCore.QRect(570, 320, 151, 51))
        self.stopCamera.setAutoFillBackground(False)
        self.stopCamera.setObjectName("stopCamera")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(570, 390, 151, 51))
        self.logout.setAutoFillBackground(False)
        self.logout.setObjectName("logout")
        main1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 26))
        self.menubar.setObjectName("menubar")
        main1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main1)
        self.statusbar.setObjectName("statusbar")
        main1.setStatusBar(self.statusbar)

        
        self.showCamera.clicked.connect(self.show)

        self.stopCamera.clicked.connect(lambda:self.exitCamera(main1))
        self.editInf.clicked.connect(lambda:self.inf_UI(main1))
        self.chooseSound.clicked.connect(self.sound_UI)
        self.logout.clicked.connect(lambda:self.logout_UI(main1))


        self.retranslateUi(main1)
        QtCore.QMetaObject.connectSlotsByName(main1)

    def exitCamera(self, main1):
        exit(main1)
    def show(self):
        driver = getDriverById(id)
        url = getSoundById(driver[5])[2]
        time = driver[6] * 1000
        print("time",time)
        run(url, time )

    def inf_UI(self, main1):
        main1.close()
        Information.idDriver = id
        self.window = QtWidgets.QMainWindow()
        self.ui =Information.Ui_frmInf()
        self.ui.setupUi(self.window)
        self.window.show()

    def sound_UI(self):
        sound.idDriver = id
        self.window = QtWidgets.QMainWindow()
        self.ui = sound.Ui_Sound()
        self.ui.setupUi(self.window)
        self.window.show()

    def logout_UI(self, main1):
        main1.close()
        self.window = QtWidgets.QMainWindow()
        self.ui =login.Ui_login()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, main1):
        _translate = QtCore.QCoreApplication.translate
        main1.setWindowTitle(_translate("main1", "MainWindow"))
        self.chooseSound.setText(_translate("main1", "Sound"))
        self.label.setText(_translate("main1", "<html><head/><body><p><span style=\" font-family:\'Georgia,Georgia,serif\'; font-size:16pt; font-weight:600; color:#444444;\">Hi Ly, welcome to Driver Drowsiness Detection System</span></p></body></html>"))
        self.editInf.setText(_translate("main1", "Personal Information"))
        self.showCamera.setText(_translate("main1", "Start"))
        self.stopCamera.setText(_translate("main1", "Stop"))
        self.logout.setText(_translate("main1", "Logout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main1 = QtWidgets.QMainWindow()
    ui = Ui_main1()
    ui.setupUi(main1)
    main1.show()
    sys.exit(app.exec_())
