# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import  login
from connectDB import *
import string
import re
import  builtins
class Ui_frmRegister(object):
    def setupUi(self, frmRegister):
        frmRegister.setObjectName("frmRegister")
        frmRegister.resize(480, 352)
        self.label = QtWidgets.QLabel(frmRegister)
        self.label.setGeometry(QtCore.QRect(180, 10, 141, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(frmRegister)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 55, 16))
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QLineEdit(frmRegister)
        self.name.setGeometry(QtCore.QRect(120, 90, 151, 21))
        self.name.setObjectName("name")
        self.label_3 = QtWidgets.QLabel(frmRegister)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 55, 16))
        self.label_3.setObjectName("label_3")
        self.age = QtWidgets.QLineEdit(frmRegister)
        self.age.setGeometry(QtCore.QRect(120, 170, 71, 21))
        self.age.setObjectName("age")
        self.label_4 = QtWidgets.QLabel(frmRegister)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 55, 16))
        self.label_4.setObjectName("label_4")
        self.license = QtWidgets.QLineEdit(frmRegister)
        self.license.setGeometry(QtCore.QRect(120, 210, 141, 21))
        self.license.setObjectName("license")
        self.btnSaveDriver = QtWidgets.QPushButton(frmRegister)
        self.btnSaveDriver.setGeometry(QtCore.QRect(120, 260, 93, 28))
        self.btnSaveDriver.setObjectName("btnSaveDriver")
        self.password = QtWidgets.QLineEdit(frmRegister)
        self.password.setGeometry(QtCore.QRect(290, 50, 141, 21))
        self.password.setObjectName("password")
        self.label_6 = QtWidgets.QLabel(frmRegister)
        self.label_6.setGeometry(QtCore.QRect(220, 50, 55, 16))
        self.label_6.setObjectName("label_6")
        self.id_driver = QtWidgets.QLineEdit(frmRegister)
        self.id_driver.setGeometry(QtCore.QRect(120, 51, 51, 21))
        self.id_driver.setReadOnly(True)
        self.id_driver.setObjectName("id_driver")
        self.label_7 = QtWidgets.QLabel(frmRegister)
        self.label_7.setGeometry(QtCore.QRect(50, 50, 55, 16))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(frmRegister)
        self.label_5.setGeometry(QtCore.QRect(120, 310, 161, 16))
        self.label_5.setObjectName("label_5")
        self.btnLogin = QtWidgets.QPushButton(frmRegister)
        self.btnLogin.setGeometry(QtCore.QRect(270, 300, 93, 28))
        self.btnLogin.setObjectName("btnLogin")
        self.label_8 = QtWidgets.QLabel(frmRegister)
        self.label_8.setGeometry(QtCore.QRect(50, 130, 55, 16))
        self.label_8.setObjectName("label_8")
        self.cbGender = QtWidgets.QComboBox(frmRegister)
        self.cbGender.setGeometry(QtCore.QRect(120, 130, 73, 22))
        self.cbGender.setObjectName("cbGender")
        self.cbGender.addItem("")
        self.cbGender.addItem("")

        self.btnLogin.clicked.connect(lambda:self.login_UI(frmRegister))
        self.btnSaveDriver.clicked.connect(lambda:self.saveDriver_UI(frmRegister))
        self.getId()

        self.retranslateUi(frmRegister)
        QtCore.QMetaObject.connectSlotsByName(frmRegister)
    def login_UI(self,frmRegister):
        frmRegister.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = login.Ui_login()
        self.ui.setupUi(self.window)
        self.window.show()

    def getId(self):
        listDriver = getDrivers()
        id = 1
        if(listDriver != []):
            if(listDriver[len(listDriver)-1]):
                driver = listDriver[len(listDriver)-1]
                id = int(driver[0]) + 1 
        self.id_driver.setText(str(id))

    def saveDriver_UI(self, frmRegister):
        id = self.id_driver.text()
        password = self.password.text()
        name = self.name.text()
        gender = self.cbGender.currentIndex()
        age = self.age.text()
        license = self.license.text()
        
        if(name == "" or password==""):
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information) 
            msg.setWindowTitle("Register fail")
            msg.setText("Name or password cannot be empty!")
            msg.exec()
        else:
            driver = {
                "id": id, 
                "password": password, 
                "name": name, 
                "gender": gender, 
                "age": age, 
                "license": license
            }
            try:
                age = driver.get("age")
                age = int(age)
                if(saveDriver(driver)):
                    msg = QtWidgets.QMessageBox()
                    msg.setIcon(QtWidgets.QMessageBox.Information) 
                    msg.setWindowTitle("Register successfully")
                    msg.setText("Register account successfully!")
                    msg.exec()
                    self.resetField()
                    self.getId()
                else:
                    msg = QtWidgets.QMessageBox()
                    msg.setIcon(QtWidgets.QMessageBox.Information) 
                    msg.setWindowTitle("Register fail")
                    msg.setText("Register fail!")
                    msg.exec()
            except:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Information) 
                msg.setWindowTitle("Register fail")
                msg.setText("Age column has data type int")
                msg.exec()
        
    def resetField(self):
        self.id_driver.setText("")
        self.name.setText("")
        self.password.setText("")
        self.name.setText("")
        self.age.setText("")
        self.license.setText("")
        self.cbGender.setCurrentIndex(0)
        
    def retranslateUi(self, frmRegister):
        _translate = QtCore.QCoreApplication.translate
        frmRegister.setWindowTitle(_translate("frmRegister", "Information"))
        self.label.setText(_translate("frmRegister", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Register</span></p></body></html>"))
        self.label_2.setText(_translate("frmRegister", "Name"))
        self.label_3.setText(_translate("frmRegister", "Age"))
        self.label_4.setText(_translate("frmRegister", "License"))
        self.btnSaveDriver.setText(_translate("frmRegister", "Register"))
        self.label_6.setText(_translate("frmRegister", "Password"))
        self.label_7.setText(_translate("frmRegister", "Id"))
        self.label_5.setText(_translate("frmRegister", "Already have an account"))
        self.btnLogin.setText(_translate("frmRegister", "Login"))
        self.label_8.setText(_translate("frmRegister", "Gender"))
        self.cbGender.setItemText(0, _translate("frmRegister", "Female"))
        self.cbGender.setItemText(1, _translate("frmRegister", "Male"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmRegister = QtWidgets.QDialog()
    ui = Ui_frmRegister()
    ui.setupUi(frmRegister)
    frmRegister.show()
    sys.exit(app.exec_())
