# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sound.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from connectDB import getSounds, getSoundById, getDriverById, updateSound, getSoundByName
soundList = []
idDriver = 1

class Ui_Sound(object):
    def setupUi(self, Sound):
        Sound.setObjectName("Sound")
        Sound.resize(480, 300)
        self.label = QtWidgets.QLabel(Sound)
        self.label.setGeometry(QtCore.QRect(210, 10, 91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Sound)
        self.label_2.setGeometry(QtCore.QRect(100, 50, 55, 21))
        self.label_2.setObjectName("label_2")
        self.cbSound = QtWidgets.QComboBox(Sound)
        self.cbSound.setGeometry(QtCore.QRect(180, 50, 191, 22))
        self.cbSound.setObjectName("cbSound")
        self.label_3 = QtWidgets.QLabel(Sound)
        self.label_3.setGeometry(QtCore.QRect(100, 90, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(Sound)
        self.label_8.setGeometry(QtCore.QRect(100, 130, 71, 21))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(Sound)
        self.label_10.setGeometry(QtCore.QRect(100, 170, 71, 21))
        self.label_10.setObjectName("label_10")
        self.btnSaveSound = QtWidgets.QPushButton(Sound)
        self.btnSaveSound.setGeometry(QtCore.QRect(220, 260, 93, 28))
        self.btnSaveSound.setObjectName("btnSaveSound")
        self.nameSong = QtWidgets.QLineEdit(Sound)
        self.nameSong.setGeometry(QtCore.QRect(180, 90, 191, 22))
        self.nameSong.setReadOnly(True)
        self.nameSong.setObjectName("nameSong")
        self.description = QtWidgets.QLineEdit(Sound)
        self.description.setGeometry(QtCore.QRect(180, 170, 191, 22))
        self.description.setReadOnly(True)
        self.description.setObjectName("description")
        self.singer = QtWidgets.QLineEdit(Sound)
        self.singer.setGeometry(QtCore.QRect(180, 130, 191, 22))
        self.singer.setReadOnly(True)
        self.singer.setObjectName("singer")
        self.label_9 = QtWidgets.QLabel(Sound)
        self.label_9.setGeometry(QtCore.QRect(100, 210, 71, 21))
        self.label_9.setObjectName("label_9")
        self.cbTimeAlarm = QtWidgets.QComboBox(Sound)
        self.cbTimeAlarm.setGeometry(QtCore.QRect(180, 210, 71, 22))
        self.cbTimeAlarm.setObjectName("cbTimeAlarm")

        self.setDataTime()
        self.cbSound.currentIndexChanged.connect(self.changeSound)
        self.setDataSound()
        self.btnSaveSound.clicked.connect(self.saveSound)

        self.retranslateUi(Sound)
        QtCore.QMetaObject.connectSlotsByName(Sound)

    def changeSound(self):
        print("change")
        index = self.cbSound.currentIndex()
        value = soundList[index]
        self.nameSong.setText(value[1])
        self.singer.setText(value[3])
        self.description.setText(value[4])
        
    def setDataSound(self):
        result = getSounds()
        for i in result:
            soundList.append(i)
            self.cbSound.addItem(i[1])
        driver = getDriverById(idDriver)
        idSound = driver[5]
        time = str(driver[6])
        self.cbSound.setCurrentText(getSoundById(idSound)[1])
        self.cbTimeAlarm.setCurrentText(time)

    def saveSound(self):
        text = self.cbSound.currentText()
        idSound = int(getSoundByName(text))
        time = int(self.cbTimeAlarm.currentText())
        if(updateSound(idDriver, idSound, time )):
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information) 
            msg.setWindowTitle("Save sound")
            msg.setText("Update sound successfully!")
            msg.exec()
        else:
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Information) 
            msg.setWindowTitle("Save sound")
            msg.setText("Update sound fail!")
            msg.exec()

    def setDataTime(self):
        listTime = [5, 10, 15, 20, 25, 30]
        for i in listTime:
            self.cbTimeAlarm.addItem(str(i))
    def retranslateUi(self, Sound):
        _translate = QtCore.QCoreApplication.translate
        Sound.setWindowTitle(_translate("Sound", "Choose Sound"))
        self.label.setText(_translate("Sound", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Sound</span></p></body></html>"))
        self.label_2.setText(_translate("Sound", "Song"))
        self.label_3.setText(_translate("Sound", "Name song"))
        self.label_8.setText(_translate("Sound", "Singer"))
        self.label_10.setText(_translate("Sound", "Description"))
        self.btnSaveSound.setText(_translate("Sound", "Save"))
        self.label_9.setText(_translate("Sound", "Time Alarm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sound = QtWidgets.QDialog()
    ui = Ui_Sound()
    ui.setupUi(Sound)
    Sound.show()
    sys.exit(app.exec_())


